export enum UserRole {
  BITFLOW_OWNER = 'BITFLOW_OWNER',
  PUBLISHER_ADMIN = 'PUBLISHER_ADMIN',
  COLLEGE_ADMIN = 'COLLEGE_ADMIN',
  COLLEGE_DEAN = 'COLLEGE_DEAN',
  COLLEGE_HOD = 'COLLEGE_HOD',
  FACULTY = 'FACULTY',
  STUDENT = 'STUDENT',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

// Phase 1: Content lifecycle status
export enum ContentStatus {
  DRAFT = 'DRAFT',
  PENDING_MAPPING = 'PENDING_MAPPING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

// Phase 1: Competency mapping status
export enum CompetencyMappingStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  COMPLETE = 'COMPLETE',
}

// Phase 1: Department status
export enum DepartmentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

// Phase 1: Faculty assignment status
export enum FacultyStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ON_LEAVE = 'ON_LEAVE',
}

export enum AuditAction {
  // Authentication
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  
  // User Management
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  
  // College Management
  COLLEGE_CREATED = 'COLLEGE_CREATED',
  COLLEGE_UPDATED = 'COLLEGE_UPDATED',
  COLLEGE_SUSPENDED = 'COLLEGE_SUSPENDED',
  COLLEGE_ACTIVATED = 'COLLEGE_ACTIVATED',
  
  // Publisher Management
  PUBLISHER_CREATED = 'PUBLISHER_CREATED',
  PUBLISHER_UPDATED = 'PUBLISHER_UPDATED',
  PUBLISHER_SUSPENDED = 'PUBLISHER_SUSPENDED',
  PUBLISHER_ACTIVATED = 'PUBLISHER_ACTIVATED',
  
  // Security Events
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  SECURITY_VIOLATION = 'SECURITY_VIOLATION',
  CONCURRENT_SESSION_LIMIT = 'CONCURRENT_SESSION_LIMIT',
  
  // Content Access
  CONTENT_ACCESSED = 'CONTENT_ACCESSED',
  CONTENT_COMPLETED = 'CONTENT_COMPLETED',
  
  // System
  SECURITY_POLICY_UPDATED = 'SECURITY_POLICY_UPDATED',

  // Phase 1: New audit actions
  // Department Management
  DEPARTMENT_CREATED = 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED',
  DEPARTMENT_DEACTIVATED = 'DEPARTMENT_DEACTIVATED',
  HOD_ASSIGNED = 'HOD_ASSIGNED',
  HOD_REMOVED = 'HOD_REMOVED',

  // Faculty Permissions
  FACULTY_PERMISSION_CREATED = 'FACULTY_PERMISSION_CREATED',
  FACULTY_PERMISSION_UPDATED = 'FACULTY_PERMISSION_UPDATED',
  FACULTY_ASSIGNED_TO_DEPARTMENT = 'FACULTY_ASSIGNED_TO_DEPARTMENT',
  FACULTY_REMOVED_FROM_DEPARTMENT = 'FACULTY_REMOVED_FROM_DEPARTMENT',
  FACULTY_PERMISSIONS_CHANGED = 'FACULTY_PERMISSIONS_CHANGED',

  // Content Lifecycle
  CONTENT_SUBMITTED_FOR_MAPPING = 'CONTENT_SUBMITTED_FOR_MAPPING',
  CONTENT_COMPETENCY_MAPPED = 'CONTENT_COMPETENCY_MAPPED',
  CONTENT_ACTIVATED = 'CONTENT_ACTIVATED',
  CONTENT_DEACTIVATED = 'CONTENT_DEACTIVATED',
  CONTENT_SUSPENDED = 'CONTENT_SUSPENDED',
  CONTENT_MAPPING_INCOMPLETE = 'CONTENT_MAPPING_INCOMPLETE',

  // Governance
  ROLE_BOUNDARY_VIOLATION = 'ROLE_BOUNDARY_VIOLATION',
  CROSS_TENANT_ACCESS_ATTEMPT = 'CROSS_TENANT_ACCESS_ATTEMPT',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  DATA_ISOLATION_BREACH_ATTEMPT = 'DATA_ISOLATION_BREACH_ATTEMPT',
}
