export * from './governance.module';
export * from './department.service';
export * from './department.controller';
export * from './faculty-permission.service';
export * from './faculty-permission.controller';
export * from './faculty-assignment.service';
export * from './faculty-assignment.controller';
export * from './guards/governance.guard';
export * from './decorators/governance.decorator';
